### PR TITLE
Fix copyright headers and formatting in new files

### PR DESCRIPTION
**Pull request by SandeepPissay**
Formatted go files and also added copyright headers to new files. 

Testing done:
1. Ran "make ci" successfully.

### CODE REVIEW

**Comment by SandeepPissay** [comment]
Prashima, please review commit# 4bb776841f3936a0bd2eb9e2db04172e2882e679 only.

**Comment by luomiao** [comment]
A better way to do the PR is first update the branch with all the commits from upstream master branch. Then commit the new change and create this PR :)

**Comment by SandeepPissay** [comment]
Miao, actually I did exactly that but not sure why this PR has other commits.

**Pull request merged**
